### ISSUE TITLE
mistake in the mixture log prob computation

### ISSUE THREAD

**Issue by junpenglao** [rlouf/blog-benchmark-rwmetropolis#2]
The mixture log prob is evaluated on the whole observation, instead of each dimension:
instead of:
```python
log_probs = np.array([dist_1(x[0]), dist_2(x[1]), dist_3(x[2]), dist_4(x[3])])
```
it should be
```python
log_probs = np.array([dist_1(x), dist_2(x), dist_3(x), dist_4(x)])
```

**Comment by junpenglao** [comment]
Also, combining the components should be `logsumexp(np.log(weights) + log_probs)`

**Comment by rlouf** [comment]
I fixed it, thank you! Go figure why I made the mistake in the JAX version but not the numpy version...
