### ISSUE TITLE
sign in logpdf

### ISSUE THREAD

**Issue by arturtoshev** [rlouf/blog-benchmark-rwmetropolis#4]
Dear contributors,

if I'm not mistaken, there is a typo in the sign of the mixture_logpdf(x) output. The last line of that function shouldn't have a minus, thus

    `return logsumexp(np.log(weights) + log_probs, axis=0)`

Fortunately, the scale of your proposal distribution is so small that the acceptance rate is close to 1. Thus the sampler does not explode and your results shouldn't change much. 

Best, AT

PS: in the blog to the notebook there is even a second minus sign in the same line, which shouldn't be there

Edit: As much as I see [Colin Carroll](https://github.com/ColCarroll/minimc) doesn't have any of the minuses

**Comment by rlouf** [comment]
Thanks for bringing this to my attention, I made the suggested corrections.
